name = "warden-worker"
main = "build/index.js"
compatibility_date = "2025-09-19"

[build]
command = "worker-build --release"

[[d1_databases]]
binding = "vault1"
database_name = "vault1"
database_id = "942279a5-121d-4c28-b90f-77cc03797b86"
